version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: desafio_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escolas_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - desafio_network

  backend:
    build: ./backend
    container_name: desafio_backend
    restart: always
    depends_on:
      - mysql
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: escolas_db
      JWT_SECRET: meusegredoseguro
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - desafio_network

  frontend:
    build: ./frontend
    container_name: desafio_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000
    networks:
      - desafio_network

volumes:
  mysql_data:

networks:
  desafio_network:
    driver: bridge